
<!DOCTYPE html>
<html lang="en" class="h-100" data-bs-theme="light">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Irving Frias | {{ page_title }}</title>
    <link rel="stylesheet" href="/css/irving-frias.min.css" media="all" />
  </head>
  <body class="d-flex flex-column h-100">
    {% include './02-header.inc' with context %}
    <main role="main">